const newPetOptions = {
  animalType: [
    {
      value: 'dog',
      label: 'Dog',
      clearableValue: false,
    }, {
      value: 'cat',
      label: 'Cat',
      clearableValue: false,
    }, {
      value: 'turtle',
      label: 'Turtle',
      clearableValue: false,
    }, {
      value: 'fish',
      label: 'Fish',
      clearableValue: false,
    }, {
      value: 'lizard',
      label: 'Lizard',
      clearableValue: false,
    }, {
      value: 'bunny',
      label: 'Bunny',
      clearableValue: false,
    }, {
      value: 'hamster',
      label: 'Hamster',
      clearableValue: false,
    }, {
      value: 'bird',
      label: 'Bird',
      clearableValue: false,
    }, {
      value: 'snake',
      label: 'Snake',
      clearableValue: false,
    }, {
      value: 'frog',
      label: 'Frog',
      clearableValue: false,
    }, {
      value: 'bat',
      label: 'Bat',
      clearableValue: false,
    }, {
      value: 'spider',
      label: 'Spider',
      clearableValue: false,
    }],
  colorOptions: [
    {
      value: 'red',
      label: 'Red',
      clearableValue: false,
    }, {
      value: 'orange',
      label: 'Orange',
      clearableValue: false,
    }, {
      value: 'yellow',
      label: 'Yellow',
      clearableValue: false,
    }, {
      value: 'green',
      label: 'Green',
      clearableValue: false,
    }, {
      value: 'blue',
      label: 'Blue',
      clearableValue: false,
    }, {
      value: 'teal',
      label: 'Teal',
      clearableValue: false,
    }, {
      value: 'purple',
      label: 'Purple',
      clearableValue: false,
    }, {
      value: 'pink',
      label: 'Pink',
      clearableValue: false,
    }, {
      value: 'peach',
      label: 'Peach',
      clearableValue: false,
    }, {
      value: 'white',
      label: 'White',
      clearableValue: false,
    }, {
      value: 'gold',
      label: 'Gold',
      clearableValue: false,
    }, {
      value: 'silver',
      label: 'Silver',
      clearableValue: false,
    }, {
      value: 'gray',
      label: 'Gray',
      clearableValue: false,
    }, {
      value: 'black',
      label: 'Black',
      clearableValue: false,
    }, {
      value: 'brown',
      label: 'Brown',
      clearableValue: false,
    }, {
      value: 'rainbow',
      label: 'Rainbow',
      clearableValue: false,
    }],
  gender: [
    {
      value: 'boy',
      label: 'Boy',
      clearableValue: false,
    }, {
      value: 'girl',
      label: 'Girl',
      clearableValue: false,
    }],

};

export default newPetOptions;
